loki: querier, add ability to adjust loki querier timeout
BitGo/kustomize-loki pull request #10
Opened 2021-08-06 09:09 UTC by biwwy0

Add ability to change this setting via envvar. 

Default value is 60s: https://grafana.com/docs/loki/latest/configuration/#querier_config

2021-08-09 00:41 UTC, james-callahan requested changes

2021-08-09 00:41 UTC, james-callahan commented on loki/files/config.yaml
> +  query_timeout: ${LOKI_QUERIER_CONFIG_QUERY_TIMEOUT:100s}
Please name this env var `LOKI_QUERIER_QUERY_TIMEOUT` -> the pattern I've been using is the path to the field in the yaml.

I think leave the default the same as loki default (`1m` https://grafana.com/docs/loki/latest/configuration/#querier_config)

2021-08-09 13:54 UTC, closed without merging

2021-08-09 13:54 UTC, biwwy0 commented
can't force push to the branch

2021-08-10 02:12 UTC, james-callahan commented
> can't force push to the branch

Please fork the repository; no one should be making branches in this repo.